name: Deploy to AWS
on:
  push:
    branches: [ "prod" ]
jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWSACCESS }}
          REMOTE_HOST: " ec2-3-16-150-103.us-east-2.compute.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/PipelineTest"

